### ISSUE TITLE
Unpacker that can rewrite deprecated paths

### ISSUE THREAD

**Issue by blinkdog** [WIPACrepo/lta#195]
Some data were archived with physical rather than logical paths (i.e. `/mnt/lfs7/IceCube/...` vs `/data/exp/IceCube`)

This issue is to:
* Add a configurable mapping, that can map N deprecated physical paths to appropriate logical paths
* Modify the Unpacker logic to accept physical paths, but automagically rewrite them to logical paths when A) placing them in the Data Warehouse and B) updating the File Catalog record

**Comment by ric-evans** [comment]
adding link to https://github.com/WIPACrepo/file_catalog/issues/98

**Comment by blinkdog** [comment]
Resolved in #197
